# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19a3QzOZMHGzCnMGm6v_7Kit3LqOxGNHY

## Streamlit Visualization Code

First, you need to install the `streamlit` library if you haven't already.
"""

!pip install streamlit

"""Now, create a Python file (e.g., `app.py`) with the following content. This code will load your prepared dataset and display a bar chart of 'Total' transportation by 'Age_Group'."""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# 
# st.set_page_config(layout="wide")
# 
# st.title('South End Transportation Analysis')
# 
# # Load the data
# @st.cache_data
# def load_data():
#     df = pd.read_csv('south_end_transportation_analysis.csv')
#     return df
# 
# df = load_data()
# 
# st.subheader('Overview of Transportation by Age Group')
# 
# # Display the dataframe (optional)
# st.write('Data Sample:', df.head())
# 
# # Create a bar chart for 'Total' transportation by 'Age_Group'
# fig = px.bar(
#     df,
#     x='Age_Group',
#     y='Total',
#     title='Total Transportation by Age Group in South End',
#     labels={'Age_Group': 'Age Group', 'Total': 'Total Transportation (%)'},
#     hover_data={'Total': ':.2f'}
# )
# 
# fig.update_layout(xaxis_title='Age Group', yaxis_title='Total Transportation (%)')
# st.plotly_chart(fig, use_container_width=True)
# 
# st.markdown("""
# ### Explanation:
# - This app loads the `south_end_transportation_analysis.csv` file.
# - It then displays a bar chart showing the 'Total' transportation percentage for each 'Age_Group'.
# - You can modify the `plotly.express` function to create different types of charts or analyze other columns.
# """)

"""### How to Run Your Streamlit App:

1.  **Save the code:** The `%%writefile app.py` command above already created the `app.py` file in your Colab environment.
2.  **Run in Colab (using `ngrok` for public access):** Streamlit apps typically run on a local server. In Colab, you can expose this server using `ngrok` to view it in your browser. Run the following commands in new code cells:

"""

!npm install localtunnel
!streamlit run app.py &>/dev/null&

!lt --port 8501

"""After running the last cell, you will get a public URL (e.g., `https://XXXX-XXXX-XXXX.loca.lt`). Open this URL in your web browser to interact with your Streamlit application.

**Note:** If `ngrok` or `localtunnel` fails, you might need to try running the Streamlit app without it and look for a local URL, then forward the port using Colab's built-in port forwarding, if available.

You can now customize `app.py` to add more visualizations and interactive elements for your presentation!
"""